import { StyleSheet } from "react-native";

export const s = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },

  container: {
    flexGrow: 1,
    width: "100%",
    alignItems: "center",
    paddingTop: 48,
    paddingBottom: 120,
    backgroundColor: "white",
  },

  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 32,
  },
  settingsBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#EFEFEF",
    backgroundColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  settingsBtnText: {
    color: "#1D1D1D",
    fontWeight: "600",
    fontSize: 14,
  },

  avatarRing: {
    width: 118,
    height: 118,
    borderRadius: 59,
    borderWidth: 3,
    borderColor: "#FDE7ED",
    overflow: "hidden",
    marginBottom: 14,
  },
  avatar: { width: "100%", height: "100%", backgroundColor: "#EFEFEF" },
  avatarOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.6)",
  },

  hint: { marginBottom: 30, fontSize: 11, color: "#666" },
  username: {
    color: "#D91B46",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  name: { fontSize: 26, fontWeight: "800", color: "#1D1D1D", lineHeight: 30, marginBottom: 18 },

  statsRow: {
    flexDirection: "row",
    width: "64%",
    minWidth: 220,
    maxWidth: 270,
    alignSelf: "center",
    justifyContent: "space-between",
  },
  statBox: {
    width: "31%",
    flexGrow: 0,
    flexShrink: 0,
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#EFEFEF",
    backgroundColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  statNumber: { width: "100%", fontSize: 20, fontWeight: "800", color: "#1D1D1D", textAlign: "center" },
  statLabel: { width: "100%", marginTop: 4, fontSize: 11, color: "#6D6D6D", textAlign: "center" },

  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  modalCard: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 16,
  },
  modalTitle: { fontSize: 16, fontWeight: "700", marginBottom: 10 },
  modalInput: {
    height: 44,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 10,
    paddingHorizontal: 12,
    fontSize: 15,
    backgroundColor: "#fff",
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 14,
  },
  modalBtn: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 10 },
  modalBtnPrimary: { backgroundColor: "#111" },
  modalBtnSecondary: { backgroundColor: "#f2f2f2" },
  modalBtnTextPrimary: { color: "#fff", fontWeight: "700" },
  modalBtnTextSecondary: { color: "#111", fontWeight: "700" },

  partnerCard: {
    borderWidth: 1,
    borderColor: "#EFEFEF",
    borderRadius: 20,
    padding: 18,
    backgroundColor: "#fff",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  partnerCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  partnerTitle: {
    color: "#D91B46",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  partnerDots: { fontSize: 20, color: "#C8C8C8", paddingHorizontal: 4 },
  partnerRow: { flexDirection: "row", alignItems: "center", gap: 14 },
  partnerAvatar: { width: 52, height: 52, borderRadius: 26, backgroundColor: "#EFEFEF", overflow: "hidden" },
  partnerName: { fontSize: 16, fontWeight: "800", color: "#1D1D1D", marginBottom: 2 },
  partnerUsername: { fontSize: 13, color: "#6D6D6D" },
  partnerDivider: { height: 1, backgroundColor: "#F2F2F2", marginVertical: 16 },
  partnerStatPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FFF0F3",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  partnerStatCount: { fontSize: 20, fontWeight: "800", color: "#D91B46" },
  partnerStatLabel: { fontSize: 13, fontWeight: "600", color: "#D91B46" },
  partnerEmptyText: { fontSize: 15, fontWeight: "700", color: "#1D1D1D", marginBottom: 6 },
  partnerEmptySubtext: { fontSize: 13, color: "#6D6D6D", lineHeight: 19 },
  partnerBody: { fontSize: 13, color: "#333" },
  partnerLink: { fontSize: 13, color: "#111", fontWeight: "800" },

  menuCard: {
    backgroundColor: "#fff",
    borderRadius: 24,
    width: "100%",
    maxWidth: 340,
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  menuHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#E0E0E0",
    alignSelf: "center",
    marginBottom: 20,
  },
  menuSheetTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: "#D91B46",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: 16,
  },
  menuDangerBtn: {
    backgroundColor: "#FFF0F3",
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: "center",
    marginBottom: 10,
  },
  menuDangerBtnText: {
    color: "#D91B46",
    fontWeight: "700",
    fontSize: 15,
  },
  menuCancelBtn: {
    backgroundColor: "#F5F5F5",
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: "center",
  },
  menuCancelBtnText: {
    color: "#1D1D1D",
    fontWeight: "600",
    fontSize: 15,
  },
  menuItem: { paddingVertical: 14, paddingHorizontal: 18 },
  menuDanger: { color: "#d11a2a", fontWeight: "700", fontSize: 15 },
  menuCancel: { color: "#111", fontWeight: "700", fontSize: 15 },

  // ── Spots section ────────────────────────────────────────────
  spotsSectionWrapper: {
    width: "100%",
    paddingHorizontal: 24,
    marginTop: 8,
  },
  spotsSectionHero: {
    marginBottom: 20,
  },
  spotsSectionEyebrow: {
    color: "#D91B46",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  spotsSectionTitle: {
    fontSize: 28,
    fontWeight: "800",
    color: "#1D1D1D",
    lineHeight: 32,
    marginBottom: 4,
  },
  spotsSectionSubtitle: {
    fontSize: 14,
    color: "#616161",
    lineHeight: 20,
  },

  spotsLoadingContainer: {
    alignItems: "center",
    paddingVertical: 32,
  },
  spotsLoadingText: {
    fontSize: 13,
    color: "#6D6D6D",
    marginTop: 10,
  },

  // ── Spot card ────────────────────────────────────────────────
  spotCard: {
    borderWidth: 1,
    borderColor: "#EFEFEF",
    borderRadius: 20,
    backgroundColor: "#fff",
    marginBottom: 20,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  spotAccentBar: {
    height: 4,
    backgroundColor: "#FDE7ED",
  },

  spotPhotoRow: {
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 16,
    paddingBottom: 10,
  },
  spotPhotoThumb: {
    width: 80,
    height: 80,
    borderRadius: 10,
    backgroundColor: "#F2F2F2",
  },

  spotHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingHorizontal: 16,
    paddingTop: 14,
    marginBottom: 10,
  },
  spotName: {
    fontSize: 17,
    fontWeight: "800",
    color: "#1D1D1D",
    flex: 1,
    marginRight: 10,
    lineHeight: 22,
  },
  spotTime: {
    fontSize: 12,
    color: "#9D9D9D",
    marginTop: 2,
  },

  // Score chips — mirrors map callout
  spotScoreRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 5,
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  chipDate: {
    backgroundColor: "#E21E4D",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  chipDateText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "800",
  },
  chipAtmo: {
    backgroundColor: "#F5F5F5",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  chipAtmoText: {
    color: "#444",
    fontSize: 12,
    fontWeight: "700",
  },
  chipReturn: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  chipReturnYes: {
    backgroundColor: "#DCFCE7",
  },
  chipReturnNo: {
    backgroundColor: "#F5F5F5",
  },
  chipReturnText: {
    fontSize: 12,
    fontWeight: "700",
  },
  chipReturnYesText: {
    color: "#16A34A",
  },
  chipReturnNoText: {
    color: "#888",
  },

  // Tag pills
  spotMeta: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    paddingHorizontal: 16,
    marginBottom: 14,
  },
  spotPill: {
    borderWidth: 1,
    borderColor: "#FDD5DE",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    fontSize: 12,
    fontWeight: "600",
    color: "#1D1D1D",
    backgroundColor: "#FFF5F7",
  },

  spotDivider: {
    height: 1,
    backgroundColor: "#F2F2F2",
    marginHorizontal: 16,
    marginBottom: 12,
  },

  spotWentWithRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 14,
    gap: 4,
  },
  spotWentWithLabel: {
    fontSize: 13,
    color: "#6D6D6D",
    fontWeight: "500",
  },
  spotWentWithUsersWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 2,
  },
  spotTaggedUser: {
    fontSize: 13,
    color: "#D91B46",
    fontWeight: "700",
  },
  spotPartnerLine: {
    fontSize: 13,
    color: "#D91B46",
    fontWeight: "700",
  },

  emptySpots: {
    alignItems: "center",
    paddingVertical: 48,
    paddingHorizontal: 20,
  },
  emptySpotsTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#1D1D1D",
    marginBottom: 6,
  },
  emptySpotsText: {
    fontSize: 14,
    color: "#6D6D6D",
    textAlign: "center",
    lineHeight: 20,
  },
});
