import { StyleSheet } from "react-native";

export const s = StyleSheet.create({
  container: {
    flexGrow: 1,
    alignItems: "center",
    paddingTop: 48,
    paddingBottom: 120,
    backgroundColor: "white",
  },

  avatar: { width: 120, height: 120, borderRadius: 60, marginBottom: 14 },
  avatarOverlay: {
    position: "absolute",
    width: 120,
    height: 120,
    borderRadius: 60,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.6)",
    top: 0,
    left: 0,
  },

  hint: { marginBottom: 30, fontSize: 11, color: "#666" },
  username: { fontSize: 14, color: "#666", marginBottom: 10 },
  name: { fontSize: 22, fontWeight: "700", marginBottom: 18 },

  statsRow: { flexDirection: "row", gap: 22 },
  statBox: {
    alignItems: "center",
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#ddd",
    minWidth: 120,
  },
  statNumber: { fontSize: 20, fontWeight: "700" },
  statLabel: { marginTop: 4, fontSize: 13, color: "#666" },

  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  modalCard: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 16,
  },
  modalTitle: { fontSize: 16, fontWeight: "700", marginBottom: 10 },
  modalInput: {
    height: 44,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 10,
    paddingHorizontal: 12,
    fontSize: 15,
    backgroundColor: "#fff",
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 14,
  },
  modalBtn: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 10 },
  modalBtnPrimary: { backgroundColor: "#111" },
  modalBtnSecondary: { backgroundColor: "#f2f2f2" },
  modalBtnTextPrimary: { color: "#fff", fontWeight: "700" },
  modalBtnTextSecondary: { color: "#111", fontWeight: "700" },

  partnerCard: {
    borderWidth: 1,
    borderColor: "#eee",
    borderRadius: 14,
    padding: 14,
    backgroundColor: "#fff",
    marginBottom: 20,
  },
  partnerTitle: { fontSize: 14, fontWeight: "800", marginBottom: 6 },
  partnerBody: { fontSize: 13, color: "#333" },
  partnerRow: { flexDirection: "row", alignItems: "center", gap: 10, marginTop: 6 },
  partnerAvatar: { width: 36, height: 36, borderRadius: 18 },
  partnerLink: { fontSize: 13, color: "#111", fontWeight: "800" },
  partnerDots: { fontSize: 22, fontWeight: "800", paddingHorizontal: 6 },

  menuCard: {
    backgroundColor: "#fff",
    borderRadius: 14,
    paddingVertical: 6,
    width: "100%",
    maxWidth: 320,
  },
  menuItem: { paddingVertical: 14, paddingHorizontal: 18 },
  menuDanger: { color: "#d11a2a", fontWeight: "700", fontSize: 15 },
  menuCancel: { color: "#111", fontWeight: "700", fontSize: 15 },

  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 14,
    color: "#111",
  },
  spotsLoadingContainer: {
    alignItems: "center",
    paddingVertical: 24,
  },
  spotsLoadingText: {
    fontSize: 13,
    color: "#666",
    marginTop: 8,
  },
  spotCard: {
    borderWidth: 1,
    borderColor: "#eee",
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    backgroundColor: "#fff",
  },
  spotHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  spotName: {
    fontSize: 16,
    fontWeight: "800",
    color: "#111",
    flex: 1,
    marginRight: 10,
  },
  spotTime: {
    fontSize: 12,
    color: "#777",
  },
  spotPhotoRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 10,
  },
  spotPhotoThumb: {
    width: 64,
    height: 64,
    borderRadius: 10,
    backgroundColor: "rgba(0,0,0,0.06)",
  },
  spotMetrics: {
    flexDirection: "row",
    gap: 14,
    marginBottom: 10,
  },
  spotMetric: {
    fontSize: 13,
    color: "#333",
  },
  spotMeta: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  spotWentWithRow: {
    marginTop: 10,
    flexDirection: "row",
    flexWrap: "wrap",
  },
  spotWentWithLabel: {
    fontSize: 13,
    color: "#444",
    fontWeight: "600",
  },
  spotWentWithUsersWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  spotTaggedUser: {
    fontSize: 13,
    color: "#1b5fc6",
    fontWeight: "700",
  },
  spotPartnerLine: {
    fontSize: 13,
    color: "#111",
    fontWeight: "800",
  },
  spotPill: {
    borderWidth: 1,
    borderColor: "#eee",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    fontSize: 12,
    color: "#111",
    backgroundColor: "#fafafa",
  },
  pillYes: {
    backgroundColor: "#f2fff7",
    borderColor: "#d6ffe6",
  },
  pillNo: {
    backgroundColor: "#fff6f6",
    borderColor: "#ffe0e0",
  },
  emptySpots: {
    alignItems: "center",
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  emptySpotsText: {
    fontSize: 13,
    color: "#666",
    textAlign: "center",
  },
});
