import { StyleSheet } from "react-native";

export const s = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },

  container: {
    flexGrow: 1,
    alignItems: "center",
    paddingTop: 48,
    paddingBottom: 120,
    backgroundColor: "white",
  },

  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 32,
  },

  avatarRing: {
    width: 118,
    height: 118,
    borderRadius: 59,
    borderWidth: 3,
    borderColor: "#FDE7ED",
    overflow: "hidden",
    marginBottom: 14,
  },
  avatar: { width: "100%", height: "100%", backgroundColor: "#EFEFEF" },

  username: {
    color: "#D91B46",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  name: { fontSize: 26, fontWeight: "800", color: "#1D1D1D", lineHeight: 30, marginBottom: 18 },

  followButton: {
    backgroundColor: "#E21E4D",
    paddingHorizontal: 28,
    paddingVertical: 9,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: "transparent",
    marginBottom: 24,
    shadowColor: "#E21E4D",
    shadowOpacity: 0.2,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  followingButton: {
    backgroundColor: "#FFF0F3",
    borderColor: "#FDD5DE",
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  followButtonText: { color: "#fff", fontWeight: "700", fontSize: 14, letterSpacing: 0.2 },
  followingButtonText: { color: "#D91B46" },

  statsRow: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 24,
    alignSelf: "stretch",
  },
  statBox: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#EFEFEF",
    backgroundColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  statNumber: { fontSize: 20, fontWeight: "800", color: "#1D1D1D" },
  statLabel: { marginTop: 4, fontSize: 11, color: "#6D6D6D", textAlign: "center" },

  partnerWrap: { width: "100%", paddingHorizontal: 24, marginTop: 24 },
  partnerCard: {
    borderWidth: 1,
    borderColor: "#EFEFEF",
    borderRadius: 20,
    padding: 18,
    backgroundColor: "#fff",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  partnerHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  partnerTitle: {
    color: "#D91B46",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  partnerDots: { fontSize: 20, color: "#C8C8C8", paddingHorizontal: 4 },
  partnerBody: { fontSize: 13, color: "#6D6D6D", lineHeight: 19 },

  primaryBtn: {
    flex: 1,
    backgroundColor: "#1D1D1D",
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: "center",
  },
  primaryBtnText: { color: "#fff", fontWeight: "700", fontSize: 14 },
  secondaryBtn: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: "#EFEFEF",
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: "center",
    backgroundColor: "#F5F5F5",
  },
  secondaryBtnText: { color: "#1D1D1D", fontWeight: "700", fontSize: 14 },

  outgoingPill: {
    borderWidth: 1.5,
    borderColor: "#EFEFEF",
    paddingVertical: 13,
    paddingHorizontal: 20,
    borderRadius: 14,
    alignItems: "center",
    backgroundColor: "#F9F9F9",
  },

  primaryWideBtn: {
    backgroundColor: "#1D1D1D",
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  primaryWideBtnText: { color: "#fff", fontWeight: "700", fontSize: 15 },

  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  menuCard: {
    backgroundColor: "#fff",
    borderRadius: 24,
    width: "100%",
    maxWidth: 340,
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  menuSheetTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: "#D91B46",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: 16,
  },
  menuDangerBtn: {
    backgroundColor: "#FFF0F3",
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: "center",
    marginBottom: 10,
  },
  menuDangerBtnText: {
    color: "#D91B46",
    fontWeight: "700",
    fontSize: 15,
  },
  menuCancelBtn: {
    backgroundColor: "#F5F5F5",
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: "center",
  },
  menuCancelBtnText: {
    color: "#1D1D1D",
    fontWeight: "600",
    fontSize: 15,
  },
  menuItem: { paddingVertical: 14, paddingHorizontal: 18 },
  menuDanger: { color: "#D91B46", fontWeight: "700", fontSize: 15 },
  menuCancel: { color: "#1D1D1D", fontWeight: "700", fontSize: 15 },
});
